import Head from 'next/head'
import ResumeComponent from 'components/Resume'
import {
  resume,
  light
} from "components/Resume/styles/variables.module.scss";
import {useAtom} from 'jotai';
import {lightTheme} from 'store.js';

export default function Resume() {
  const [theme] = useAtom(lightTheme);
  return (
    <>
      <Head>
        <title> Resume | Pierre Pellegrino </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={`${resume} ${theme && light}`}>
        <ResumeComponent />
      </div>
    </>
  )
}
