import Head from 'next/head'
import ResumeComponent from 'components/Resume'
import {
  resume,
} from "components/Resume/styles/variables.module.scss";

export default function Resume() {

  return (
    <>
      <Head>
        <title> Resume | Pierre Pellegrino </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={resume}>
        <ResumeComponent />
      </div>
    </>
  )
}
